version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app-container
    environment:
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_HOST: postgres
      DB_PORT: 5432
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
